### ISSUE TITLE
Featured image

### ISSUE THREAD

**Issue by amaehrer** [TheTempleNews/longform#9]
Can we raise the height for the featured image and possibly remove the overlay that's covering it? If it would interfere with the text, could we move the headline/dek closer to the top of the image?

**Comment by astratagem** [comment]
IMO it looks pretty good as it is and I suggest making as few edits to the
theme as possible. The theme is meant to be spacious and breathable –
constricting the masthead to save space or whatever would take away from
the design as a whole. As for the overlay text, that should remain because
the text would be unreadable without it…

On Sun, Aug 24, 2014 at 10:17 AM, amaehrer notifications@github.com wrote:

> Can we raise the height for the featured image and possibly remove the
> overlay behind it? If it would interfere with the text, could we move the
> headline/dek closer to the top of the image?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TheTempleNews/longform/issues/9.

## 

_Chris Montgomery_
chris@montchr.io
github.com/montchr

Web Developer
School of Media and Communication
Temple University
smc.temple.edu
fork@temple.edu

Web Editor
The Temple News
temple-news.com
web@temple-news.com

Vice President
Aperture Agency
apertureagency@gmail.com

_Sous les pavés, la plage_.
